controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_group_controller:
  ros__parameters:
    joints:
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_group_controller:
  ros__parameters:
    joints:
      - gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

head_group_controller:
  ros__parameters:
    joints:
      - head_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity