slam_toolbox:
  ros__parameters:
    # Solver settings
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping

    # NO-ODOM TUNING
    use_scan_matching: true
    use_scan_barycenter: true
    # We set these low so SLAM updates even with tiny movements
    minimum_travel_distance: 0.05 
    minimum_travel_heading: 0.05
    scan_buffer_size: 15
    scan_buffer_maximum_scan_distance: 10.0
    
    # Matching strictness (0.1 to 0.3 is usually good)
    link_match_minimum_response_fine: 0.15  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true